version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/vida_coach
      - OPENAI_API_KEY=${OPENAI_API_KEY:-test}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-whsec_test}
      - SECRET_KEY=${SECRET_KEY:-test}
      - RATE_LIMIT=${RATE_LIMIT:-100/minute}
      - TESTING=true
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=vida_coach
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
