// Page providing a simple interface for AI coaching prompts
// The UI collects a question from the user and displays the response
// generated by the backend AI service.
'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { getAiResponse } from '../../services/aiCoachService';
import { getToken, isTokenExpired } from '../../services/authUtils';
import { showError } from '../../components/ToastProvider';

export default function CoachPage() {
  const router = useRouter(); // Notes: Router used for redirects
  // Local state for the prompt text entered by the user
  const [prompt, setPrompt] = useState('');
  // Local state for the displayed AI response
  // Initially show placeholder text until the user submits a prompt
  const [response, setResponse] = useState('AI response will appear here');
  // Track loading state while waiting for backend
  const [loading, setLoading] = useState(false);
  // Track error message on failure
  const [error, setError] = useState('');

  // Notes: Validate the JWT on initial render and logout if expired
  useEffect(() => {
    const token = getToken();
    if (!token || isTokenExpired(token)) {
      localStorage.removeItem('token');
      showError('Session expired. Please login again.');
      router.push('/login');
    }
  }, [router]);

  // Handler for sending the prompt
  // Invoked when the user clicks the send button
  const handleSend = async () => {
    // Reset status and show spinner
    setLoading(true);
    setError('');
    try {
      // Fetch the AI response from the backend service
      const aiText = await getAiResponse(prompt);
      setResponse(aiText);
    } catch (err) {
      // Show generic error message if request fails
      setError('Failed to fetch AI response.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-screen p-4 space-y-4">
      {/* Navigation back to dashboard */}
      <Link href="/dashboard" className="self-start text-blue-600 underline">
        Back to Dashboard
      </Link>

      {/* Title of the page */}
      <h1 className="text-2xl font-bold">AI Coach</h1>

      {/* Text area for user prompt */}
      <textarea
        className="border rounded p-2 w-full max-w-md"
        value={prompt}
        onChange={(e) => setPrompt(e.target.value)}
        placeholder="Ask a question..."
      />

      {/* Button to submit the prompt */}
      <button
        onClick={handleSend}
        className="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700"
      >
        Send Prompt
      </button>
      {/* Display spinner during API call */}
      {loading && (
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900" />
      )}
      {/* Display error message if fetch failed */}
      {error && <p className="text-red-600">{error}</p>}

      {/* Area showing the AI response */}
      <div className="border rounded p-4 bg-gray-100 w-full max-w-md text-center">
        {response}
      </div>
    </div>
  );
}
