from pydantic import BaseModel
from datetime import datetime


class JournalEntryCreate(BaseModel):
    """Model for creating a journal entry."""

    user_id: int
    title: str | None = None
    content: str
    # Optional goal to associate with this journal entry
    linked_goal_id: int | None = None
    # Indicates whether the journal was generated by an AI agent
    ai_generated: bool | None = False


class JournalEntryResponse(BaseModel):
    """Model for returning journal entry information."""

    id: int
    user_id: int
    title: str | None = None
    content: str
    # Include the linked goal id in responses
    linked_goal_id: int | None = None
    created_at: datetime
    updated_at: datetime
    # Indicates whether the journal was generated by an AI agent
    ai_generated: bool = False

    class Config:
        orm_mode = True
