name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Python deps
        run: pip install -r requirements.txt
      - name: Install frontend deps
        run: |
          cd frontend
          npm install
      - name: Run backend tests
        run: pytest -q --disable-warnings
      - name: Run frontend unit tests
        run: |
          cd frontend
          npm run test:unit -- --maxWorkers=50%

